version: '3.8'

services:
  eureka-server:
    image: steeltoeoss/eureka-server:latest
    ports:
      - "8761:8761"
    environment:
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"

  postgres-customers:
    image: postgres:15
    environment:
      POSTGRES_DB: customers_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - customers_data:/var/lib/postgresql/data

  postgres-accounts:
    image: postgres:15
    environment:
      POSTGRES_DB: accounts_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5434:5432"
    volumes:
      - accounts_data:/var/lib/postgresql/data

  ms-customers:
    build: ./ms-customers
    ports:
      - "8081:8081"
    depends_on:
      - postgres-customers
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-customers:5432/customers_db
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_APPLICATION_NAME: ms-customers
      JWT_SECRET: mySecretKeyForJWTGenerationWithMinimumLengthAndStrongRandomCharacters

  ms-accounts:
    build: ./ms-accounts
    ports:
      - "8082:8082"
    depends_on:
      - postgres-accounts
      - ms-customers
      - eureka-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-accounts:5432/accounts_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      CUSTOMERS_SERVICE_URL: http://ms-customers:8081
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_APPLICATION_NAME: ms-accounts
      JWT_SECRET: mySecretKeyForJWTGenerationWithMinimumLengthAndStrongRandomCharacters

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - ms-customers
      - ms-accounts
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_APPLICATION_NAME: api-gateway
      JWT_SECRET: mySecretKeyForJWTGenerationWithMinimumLengthAndStrongRandomCharacters
volumes:
  customers_data:
  accounts_data: