server:
  port: 8081

spring:
  application:
    name: ms-customers

  datasource:
    url: jdbc:postgresql://localhost:5433/customers_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # Para desarrollo, en producción usar 'validate' o 'none'
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

jwt:
  secret: ${JWT_SECRET:mySecretKey}   # Usa variable de entorno en producción
  expiration: 3600000                # 1 hora en milisegundos

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG