server:
  port: 8081

spring:
  application:
    name: ms-customers

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/customers_db}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWTGenerationWithMinimumLengthAndStrongRandomCharacters}   # Usa variable de entorno en producciï¿½n
  expiration: 3600000

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:ms-customers}